apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "corevpn.fullname" . }}-config
  labels:
    {{- include "corevpn.labels" . | nindent 4 }}
data:
  config.toml: |
    {{- include "corevpn.configToml" . | nindent 4 }}
