{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "corevpn.serviceAccountName" . }}
  labels:
    {{- include "corevpn.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "corevpn.fullname" . }}
  labels:
    {{- include "corevpn.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames:
      - {{ include "corevpn.secretName" . }}
      - {{ include "corevpn.pkiSecretName" . }}
    verbs: ["get"]
  - apiGroups: [""]
    resources: ["configmaps"]
    resourceNames:
      - {{ include "corevpn.fullname" . }}-config
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "corevpn.fullname" . }}
  labels:
    {{- include "corevpn.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "corevpn.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "corevpn.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
